before_script:
  - psql -c 'create database babyfoot;' -U postgres
os:
  - linux
  - osx
language: node_js
node_js:
  - 12
dist: xenial
sudo: required
services:
  - xvfb
before_script:
  - export DISPLAY=:99.0
install:
  - npm set progress=false
  - npm install
script:
  - npx eslint ./
  - ng test
